export const TOGGLE_FIRST_NAME = 'TOGGLE_FIRST_NAME';
export const TOGGLE_LAST_NAME = 'TOGGLE_LAST_NAME';
export const SET_TOGGLE_FIRST_NAME = 'SET_TOGGLE_FIRST_NAME';
export const SET_TOGGLE_LAST_NAME = 'SET_TOGGLE_LAST_NAME';


export const SET_LABEL_BACKGROUND = 'SET_LABEL_BACKGROUND';
export const SET_HEADING_FONT_FAMILY = 'SET_HEADING_FONT_FAMILY';
export const SET_HEADING_FONT_SIZE = 'SET_HEADING_FONT_SIZE';
export const SET_HEADING_BOLD = 'SET_HEADING_BOLD';
export const SET_HEADING_ITALIC = 'SET_HEADING_ITALIC';
export const SET_HEADING_UNDERLINE = 'SET_HEADING_UNDERLINE';
export const SET_HEADING_TEXT_ALIGN = 'SET_HEADING_TEXT_ALIGN';
export const SET_HEADING_TEXT = 'SET_HEADING_TEXT';
export const SET_HEADING_COLOR = 'SET_HEADING_COLOR';

export const SET_SUBTITLE_FONT_FAMILY = 'SET_SUBTITLE_FONT_FAMILY';
export const SET_SUBTITLE_FONT_SIZE = 'SET_SUBTITLE_FONT_SIZE';
export const SET_SUBTITLE_BOLD = 'SET_SUBTITLE_BOLD';
export const SET_SUBTITLE_ITALIC = 'SET_SUBTITLE_ITALIC';
export const SET_SUBTITLE_UNDERLINE = 'SET_SUBTITLE_UNDERLINE';
export const SET_SUBTITLE_TEXT_ALIGN = 'SET_SUBTITLE_TEXT_ALIGN';
export const SET_SUBTITLE_TEXT = 'SET_SUBTITLE_TEXT';
export const SET_SUBTITLE_COLOR = 'SET_SUBTITLE_COLOR';

export const SET_BUTTON_FONT_FAMILY = 'SET_BUTTON_FONT_FAMILY';
export const SET_BUTTON_FONT_SIZE = 'SET_BUTTON_FONT_SIZE';
export const SET_BUTTON_BOLD = 'SET_BUTTON_BOLD';
export const SET_BUTTON_ITALIC = 'SET_BUTTON_ITALIC';
export const SET_BUTTON_UNDERLINE = 'SET_BUTTON_UNDERLINE';
export const SET_BUTTON_BACKGROUND = 'SET_BUTTON_BACKGROUND';
export const SET_BUTTON_TEXT = 'SET_BUTTON_TEXT'
export const SET_BUTTON_TEXT_COLOR = 'SET_BUTTON_TEXT_COLOR'


export const SET_MODAL_OPEN = 'SET_MODAL_OPEN';

// Preview ID

export const SET_PREVIEW_ID = 'SET_PREVIEW_ID'